<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>^.*?Successfully?</string>
                <key>name</key>
                <string>markup.italic.restructuredtext</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\[DEPLOYMENT FAILED\]?</string>
                <key>name</key>
                <string>invalid.illegal.unexpected-text.test_case_results</string>
            </dict>
        </array>
        <key>name</key>
        <string>Test case results custom syntax</string>
        <key>scopeName</key>
        <string>source.test_case_results</string>
    </dict>
</plist>